require("./formats");
require("./transformers");

const { groups } = require("./transformers");

const outputDirIndex = process.argv.findIndex((arg) => arg === "--output-dir");
const outputDir = process.argv[outputDirIndex + 1];

if (outputDirIndex === -1 || !outputDir) {
  console.error("ERROR: No output directory specified. Pass the --output-dir argument to the script.");
  process.exit(1);
}

const variableName = 'designTokens';
const fileName = 'tokens';

// Predefined transform groups
// https://amzn.github.io/style-dictionary/#/transform_groups?id=pre-defined-transform-groups
module.exports = {
  source: ["design_tokens/**/*.json"],
  fileHeader: {
    default: () => {
      return [
        "This file is automatically generated. Do not edit it directly.",
        "Checkout README for more information on how to add a new variable.",
        "Generated on " + new Date()
      ];
    },
  },
  platforms: {
    css: {
      transformGroup: "css",
      transforms: ["attribute/cti", "content/icon", "name/cti/kebab", "size/px", "time/seconds", ...groups["stylesheet"]],
      files: [
        {
          destination: `${outputDir}/styles/${fileName}.css`,
          format: "css/variables",
          options: {
            outputReferences: true,
            fileHeader: "default",
          },
        },
      ],
    },
    scss: {
      transformGroup: "scss",
      transforms: ["attribute/cti", "content/icon", "name/cti/kebab", "size/px", "time/seconds", ...groups["stylesheet"]],
      files: [
        {
          format: "scss/map-deep",
          destination: `${outputDir}/styles/${fileName}.scss`,
          mapName: variableName,
          fileHeader: "default",
        },
      ],
    },
    js: {
      transformGroup: "js",
      transforms: ["attribute/cti", "name/cti/kebab"],
      files: [
        {
          format: "javascript/module",
          destination: `${outputDir}/js/${fileName}.js`,
          options: {
            variableName: variableName,
            fileHeader: "default",
          },
        },
      ],
    },
    web: {
      transformGroup: "web",
      transforms: ["attribute/cti", "name/cti/kebab"],
      files: [
        {
          format: "custom/typescript",
          destination: `${outputDir}/ts/${fileName}.ts`,
          options: {
            variableName: variableName,
            fileHeader: "default",
          },
        },
      ],
    },
    native: {
      transformGroup: "react-native",
      transforms: ["attribute/cti", "name/cti/kebab", "color/css", "size/object"],
      files: [
        {
          format: "custom/typescript",
          destination: `${outputDir}/ts/${fileName}.native.ts`,
          options: {
            variableName: variableName,
            fileHeader: "default",
          },
        },
      ],
    },
  },
};
