/**
 * This file is automatically generated. Do not edit it directly.
 * Checkout README for more information on how to add a new variable.
 * Generated on Wed Jan 03 2024 18:08:05 GMT+0100 (Central European Standard Time)
 */

module.exports = {
  "font-size": {
    "10": {
      "value": "10",
      "unit": "px",
      "type": "fontSizes",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": "10",
        "unit": "px",
        "type": "fontSizes"
      },
      "name": "font-size-10",
      "attributes": {
        "category": "font-size",
        "type": "10"
      },
      "path": [
        "font-size",
        "10"
      ]
    },
    "12": {
      "value": "12",
      "unit": "px",
      "type": "fontSizes",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": "12",
        "unit": "px",
        "type": "fontSizes"
      },
      "name": "font-size-12",
      "attributes": {
        "category": "font-size",
        "type": "12"
      },
      "path": [
        "font-size",
        "12"
      ]
    },
    "14": {
      "value": "14",
      "unit": "px",
      "type": "fontSizes",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": "14",
        "unit": "px",
        "type": "fontSizes"
      },
      "name": "font-size-14",
      "attributes": {
        "category": "font-size",
        "type": "14"
      },
      "path": [
        "font-size",
        "14"
      ]
    },
    "16": {
      "value": "16",
      "unit": "px",
      "type": "fontSizes",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": "16",
        "unit": "px",
        "type": "fontSizes"
      },
      "name": "font-size-16",
      "attributes": {
        "category": "font-size",
        "type": "16"
      },
      "path": [
        "font-size",
        "16"
      ]
    },
    "18": {
      "value": "18",
      "unit": "px",
      "type": "fontSizes",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": "18",
        "unit": "px",
        "type": "fontSizes"
      },
      "name": "font-size-18",
      "attributes": {
        "category": "font-size",
        "type": "18"
      },
      "path": [
        "font-size",
        "18"
      ]
    }
  },
  "font-weight": {
    "regular": {
      "value": "400",
      "type": "fontWeights",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": "400",
        "type": "fontWeights"
      },
      "name": "font-weight-regular",
      "attributes": {
        "category": "font-weight",
        "type": "regular"
      },
      "path": [
        "font-weight",
        "regular"
      ]
    },
    "semi-bold": {
      "value": "600",
      "type": "fontWeights",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": "600",
        "type": "fontWeights"
      },
      "name": "font-weight-semi-bold",
      "attributes": {
        "category": "font-weight",
        "type": "semi-bold"
      },
      "path": [
        "font-weight",
        "semi-bold"
      ]
    },
    "bold": {
      "value": "800",
      "type": "fontWeights",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": "800",
        "type": "fontWeights"
      },
      "name": "font-weight-bold",
      "attributes": {
        "category": "font-weight",
        "type": "bold"
      },
      "path": [
        "font-weight",
        "bold"
      ]
    }
  },
  "font-family": {
    "value": "Roboto",
    "variable": "--font-roboto",
    "type": "fontFamilies",
    "filePath": "design_tokens/custom.json",
    "isSource": true,
    "original": {
      "value": "Roboto",
      "variable": "--font-roboto",
      "type": "fontFamilies"
    },
    "name": "font-family",
    "attributes": {
      "category": "font-family"
    },
    "path": [
      "font-family"
    ]
  },
  "letter-spacing": {
    "default": {
      "value": "2%",
      "type": "letterSpacing",
      "unit": "em",
      "calculate": "[value] / 100",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": "2%",
        "type": "letterSpacing",
        "unit": "em",
        "calculate": "[value] / 100"
      },
      "name": "letter-spacing-default",
      "attributes": {
        "category": "letter-spacing",
        "type": "default"
      },
      "path": [
        "letter-spacing",
        "default"
      ]
    },
    "increased": {
      "value": "15%",
      "type": "letterSpacing",
      "unit": "em",
      "calculate": "[value] / 100",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": "15%",
        "type": "letterSpacing",
        "unit": "em",
        "calculate": "[value] / 100"
      },
      "name": "letter-spacing-increased",
      "attributes": {
        "category": "letter-spacing",
        "type": "increased"
      },
      "path": [
        "letter-spacing",
        "increased"
      ]
    },
    "decreased": {
      "value": "-3%",
      "type": "letterSpacing",
      "unit": "em",
      "calculate": "[value] / 100",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": "-3%",
        "type": "letterSpacing",
        "unit": "em",
        "calculate": "[value] / 100"
      },
      "name": "letter-spacing-decreased",
      "attributes": {
        "category": "letter-spacing",
        "type": "decreased"
      },
      "path": [
        "letter-spacing",
        "decreased"
      ]
    }
  },
  "border-radius": {
    "1": {
      "value": "1",
      "type": "borderRadius",
      "unit": "px",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": "1",
        "type": "borderRadius",
        "unit": "px"
      },
      "name": "border-radius-1",
      "attributes": {
        "category": "border-radius",
        "type": "1"
      },
      "path": [
        "border-radius",
        "1"
      ]
    },
    "2": {
      "value": "2",
      "type": "borderRadius",
      "unit": "px",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": "2",
        "type": "borderRadius",
        "unit": "px"
      },
      "name": "border-radius-2",
      "attributes": {
        "category": "border-radius",
        "type": "2"
      },
      "path": [
        "border-radius",
        "2"
      ]
    },
    "4": {
      "value": "4",
      "type": "borderRadius",
      "unit": "px",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": "4",
        "type": "borderRadius",
        "unit": "px"
      },
      "name": "border-radius-4",
      "attributes": {
        "category": "border-radius",
        "type": "4"
      },
      "path": [
        "border-radius",
        "4"
      ]
    },
    "8": {
      "value": "8",
      "type": "borderRadius",
      "unit": "px",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": "8",
        "type": "borderRadius",
        "unit": "px"
      },
      "name": "border-radius-8",
      "attributes": {
        "category": "border-radius",
        "type": "8"
      },
      "path": [
        "border-radius",
        "8"
      ]
    }
  },
  "border-width": {
    "1": {
      "value": "1",
      "type": "borderWidth",
      "unit": "px",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": "1",
        "type": "borderWidth",
        "unit": "px"
      },
      "name": "border-width-1",
      "attributes": {
        "category": "border-width",
        "type": "1"
      },
      "path": [
        "border-width",
        "1"
      ]
    },
    "2": {
      "value": "2",
      "type": "borderWidth",
      "unit": "px",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": "2",
        "type": "borderWidth",
        "unit": "px"
      },
      "name": "border-width-2",
      "attributes": {
        "category": "border-width",
        "type": "2"
      },
      "path": [
        "border-width",
        "2"
      ]
    }
  },
  "box-shadow": {
    "v1": {
      "value": {
        "x": "0",
        "y": "3",
        "blur": "5",
        "spread": "0",
        "color": "rgba(0, 0, 0, 0.2)",
        "type": "dropShadow"
      },
      "type": "boxShadow",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": {
          "x": "0",
          "y": "3",
          "blur": "5",
          "spread": "0",
          "color": "rgba(0, 0, 0, 0.2)",
          "type": "dropShadow"
        },
        "type": "boxShadow"
      },
      "name": "box-shadow-v1",
      "attributes": {
        "category": "box-shadow",
        "type": "v1"
      },
      "path": [
        "box-shadow",
        "v1"
      ]
    },
    "v2": {
      "value": {
        "x": "0",
        "y": "4",
        "blur": "16",
        "spread": "0",
        "color": "rgba(0, 0, 0, 0.1)",
        "type": "dropShadow"
      },
      "type": "boxShadow",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": {
          "x": "0",
          "y": "4",
          "blur": "16",
          "spread": "0",
          "color": "rgba(0, 0, 0, 0.1)",
          "type": "dropShadow"
        },
        "type": "boxShadow"
      },
      "name": "box-shadow-v2",
      "attributes": {
        "category": "box-shadow",
        "type": "v2"
      },
      "path": [
        "box-shadow",
        "v2"
      ]
    },
    "v3": {
      "value": [
        {
          "x": "0",
          "y": "7",
          "blur": "50",
          "spread": "0",
          "color": "rgba(0, 0, 0, 0.2)",
          "type": "dropShadow"
        },
        {
          "x": "0",
          "y": "3",
          "blur": "5",
          "spread": "0",
          "color": "rgba(0, 0, 0, 0.2)",
          "type": "dropShadow"
        }
      ],
      "type": "boxShadow",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": [
          {
            "x": "0",
            "y": "7",
            "blur": "50",
            "spread": "0",
            "color": "rgba(0, 0, 0, 0.2)",
            "type": "dropShadow"
          },
          {
            "x": "0",
            "y": "3",
            "blur": "5",
            "spread": "0",
            "color": "rgba(0, 0, 0, 0.2)",
            "type": "dropShadow"
          }
        ],
        "type": "boxShadow"
      },
      "name": "box-shadow-v3",
      "attributes": {
        "category": "box-shadow",
        "type": "v3"
      },
      "path": [
        "box-shadow",
        "v3"
      ]
    }
  },
  "zIndex": {
    "background": {
      "value": -1,
      "type": "integer",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": -1,
        "type": "integer"
      },
      "name": "z-index-background",
      "attributes": {
        "category": "zIndex",
        "type": "background"
      },
      "path": [
        "zIndex",
        "background"
      ]
    },
    "content": {
      "value": 0,
      "type": "integer",
      "comment": "Default z-index for all elements",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": 0,
        "type": "integer",
        "comment": "Default z-index for all elements"
      },
      "name": "z-index-content",
      "attributes": {
        "category": "zIndex",
        "type": "content"
      },
      "path": [
        "zIndex",
        "content"
      ]
    },
    "contentHighlighted": {
      "value": 10,
      "type": "integer",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": 10,
        "type": "integer"
      },
      "name": "z-index-content-highlighted",
      "attributes": {
        "category": "zIndex",
        "type": "contentHighlighted"
      },
      "path": [
        "zIndex",
        "contentHighlighted"
      ]
    },
    "header": {
      "value": 20,
      "type": "integer",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": 20,
        "type": "integer"
      },
      "name": "z-index-header",
      "attributes": {
        "category": "zIndex",
        "type": "header"
      },
      "path": [
        "zIndex",
        "header"
      ]
    },
    "drawer": {
      "value": 30,
      "type": "integer",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": 30,
        "type": "integer"
      },
      "name": "z-index-drawer",
      "attributes": {
        "category": "zIndex",
        "type": "drawer"
      },
      "path": [
        "zIndex",
        "drawer"
      ]
    },
    "overlay": {
      "value": 40,
      "type": "integer",
      "filePath": "design_tokens/custom.json",
      "isSource": true,
      "original": {
        "value": 40,
        "type": "integer"
      },
      "name": "z-index-overlay",
      "attributes": {
        "category": "zIndex",
        "type": "overlay"
      },
      "path": [
        "zIndex",
        "overlay"
      ]
    }
  },
  "colors": {
    "white": {
      "value": "rgb(255, 255, 255)",
      "metadata": {
        "source": {
          "styleguide": {
            "id": "6593c96ec4165528ed2a9575",
            "name": "Core",
            "platform": "base"
          }
        },
        "resource": {
          "id": "6593e53320c750a08510cf28",
          "type": "Color"
        }
      },
      "filePath": "design_tokens/zeplin.json",
      "isSource": true,
      "original": {
        "value": "rgb(255, 255, 255)",
        "metadata": {
          "source": {
            "styleguide": {
              "id": "6593c96ec4165528ed2a9575",
              "name": "Core",
              "platform": "base"
            }
          },
          "resource": {
            "id": "6593e53320c750a08510cf28",
            "type": "Color"
          }
        }
      },
      "name": "colors-white",
      "attributes": {
        "category": "colors",
        "type": "white"
      },
      "path": [
        "colors",
        "white"
      ]
    },
    "greyDark": {
      "value": "rgb(110, 110, 110)",
      "metadata": {
        "source": {
          "styleguide": {
            "id": "6593c96ec4165528ed2a9575",
            "name": "Core",
            "platform": "base"
          }
        },
        "resource": {
          "id": "6593e5365d72b0034cf470d5",
          "type": "Color"
        }
      },
      "filePath": "design_tokens/zeplin.json",
      "isSource": true,
      "original": {
        "value": "rgb(110, 110, 110)",
        "metadata": {
          "source": {
            "styleguide": {
              "id": "6593c96ec4165528ed2a9575",
              "name": "Core",
              "platform": "base"
            }
          },
          "resource": {
            "id": "6593e5365d72b0034cf470d5",
            "type": "Color"
          }
        }
      },
      "name": "colors-grey-dark",
      "attributes": {
        "category": "colors",
        "type": "greyDark"
      },
      "path": [
        "colors",
        "greyDark"
      ]
    },
    "purple": {
      "value": "rgb(57, 54, 117)",
      "metadata": {
        "source": {
          "styleguide": {
            "id": "6593c96ec4165528ed2a9575",
            "name": "Core",
            "platform": "base"
          }
        },
        "resource": {
          "id": "6593e533261417303c12415e",
          "type": "Color"
        }
      },
      "filePath": "design_tokens/zeplin.json",
      "isSource": true,
      "original": {
        "value": "rgb(57, 54, 117)",
        "metadata": {
          "source": {
            "styleguide": {
              "id": "6593c96ec4165528ed2a9575",
              "name": "Core",
              "platform": "base"
            }
          },
          "resource": {
            "id": "6593e533261417303c12415e",
            "type": "Color"
          }
        }
      },
      "name": "colors-purple",
      "attributes": {
        "category": "colors",
        "type": "purple"
      },
      "path": [
        "colors",
        "purple"
      ]
    },
    "red": {
      "value": "rgb(181, 69, 69)",
      "metadata": {
        "source": {
          "styleguide": {
            "id": "6593c96ec4165528ed2a9575",
            "name": "Core",
            "platform": "base"
          }
        },
        "resource": {
          "id": "6593e534cf09fb912ef8ec11",
          "type": "Color"
        }
      },
      "filePath": "design_tokens/zeplin.json",
      "isSource": true,
      "original": {
        "value": "rgb(181, 69, 69)",
        "metadata": {
          "source": {
            "styleguide": {
              "id": "6593c96ec4165528ed2a9575",
              "name": "Core",
              "platform": "base"
            }
          },
          "resource": {
            "id": "6593e534cf09fb912ef8ec11",
            "type": "Color"
          }
        }
      },
      "name": "colors-red",
      "attributes": {
        "category": "colors",
        "type": "red"
      },
      "path": [
        "colors",
        "red"
      ]
    },
    "yellow": {
      "value": "rgb(226, 158, 48)",
      "metadata": {
        "source": {
          "styleguide": {
            "id": "6593c96ec4165528ed2a9575",
            "name": "Core",
            "platform": "base"
          }
        },
        "resource": {
          "id": "6593e534d578f42e327a7711",
          "type": "Color"
        }
      },
      "filePath": "design_tokens/zeplin.json",
      "isSource": true,
      "original": {
        "value": "rgb(226, 158, 48)",
        "metadata": {
          "source": {
            "styleguide": {
              "id": "6593c96ec4165528ed2a9575",
              "name": "Core",
              "platform": "base"
            }
          },
          "resource": {
            "id": "6593e534d578f42e327a7711",
            "type": "Color"
          }
        }
      },
      "name": "colors-yellow",
      "attributes": {
        "category": "colors",
        "type": "yellow"
      },
      "path": [
        "colors",
        "yellow"
      ]
    },
    "blue": {
      "value": "rgb(40, 151, 189)",
      "metadata": {
        "source": {
          "styleguide": {
            "id": "6593c96ec4165528ed2a9575",
            "name": "Core",
            "platform": "base"
          }
        },
        "resource": {
          "id": "6593e535e95324860d9c265a",
          "type": "Color"
        }
      },
      "filePath": "design_tokens/zeplin.json",
      "isSource": true,
      "original": {
        "value": "rgb(40, 151, 189)",
        "metadata": {
          "source": {
            "styleguide": {
              "id": "6593c96ec4165528ed2a9575",
              "name": "Core",
              "platform": "base"
            }
          },
          "resource": {
            "id": "6593e535e95324860d9c265a",
            "type": "Color"
          }
        }
      },
      "name": "colors-blue",
      "attributes": {
        "category": "colors",
        "type": "blue"
      },
      "path": [
        "colors",
        "blue"
      ]
    },
    "blueLink": {
      "value": "rgb(15, 76, 168)",
      "metadata": {
        "source": {
          "styleguide": {
            "id": "6593c96ec4165528ed2a9575",
            "name": "Core",
            "platform": "base"
          }
        },
        "resource": {
          "id": "6593e5368bb13bbcabd6c7a9",
          "type": "Color"
        }
      },
      "filePath": "design_tokens/zeplin.json",
      "isSource": true,
      "original": {
        "value": "rgb(15, 76, 168)",
        "metadata": {
          "source": {
            "styleguide": {
              "id": "6593c96ec4165528ed2a9575",
              "name": "Core",
              "platform": "base"
            }
          },
          "resource": {
            "id": "6593e5368bb13bbcabd6c7a9",
            "type": "Color"
          }
        }
      },
      "name": "colors-blue-link",
      "attributes": {
        "category": "colors",
        "type": "blueLink"
      },
      "path": [
        "colors",
        "blueLink"
      ]
    },
    "green": {
      "value": "rgb(0, 173, 147)",
      "metadata": {
        "source": {
          "styleguide": {
            "id": "6593c96ec4165528ed2a9575",
            "name": "Core",
            "platform": "base"
          }
        },
        "resource": {
          "id": "6593e535261417303c124250",
          "type": "Color"
        }
      },
      "filePath": "design_tokens/zeplin.json",
      "isSource": true,
      "original": {
        "value": "rgb(0, 173, 147)",
        "metadata": {
          "source": {
            "styleguide": {
              "id": "6593c96ec4165528ed2a9575",
              "name": "Core",
              "platform": "base"
            }
          },
          "resource": {
            "id": "6593e535261417303c124250",
            "type": "Color"
          }
        }
      },
      "name": "colors-green",
      "attributes": {
        "category": "colors",
        "type": "green"
      },
      "path": [
        "colors",
        "green"
      ]
    },
    "grey": {
      "value": "rgb(230, 230, 230)",
      "metadata": {
        "source": {
          "styleguide": {
            "id": "6593c96ec4165528ed2a9575",
            "name": "Core",
            "platform": "base"
          }
        },
        "resource": {
          "id": "6593e5353ae10af9c77de983",
          "type": "Color"
        }
      },
      "filePath": "design_tokens/zeplin.json",
      "isSource": true,
      "original": {
        "value": "rgb(230, 230, 230)",
        "metadata": {
          "source": {
            "styleguide": {
              "id": "6593c96ec4165528ed2a9575",
              "name": "Core",
              "platform": "base"
            }
          },
          "resource": {
            "id": "6593e5353ae10af9c77de983",
            "type": "Color"
          }
        }
      },
      "name": "colors-grey",
      "attributes": {
        "category": "colors",
        "type": "grey"
      },
      "path": [
        "colors",
        "grey"
      ]
    },
    "charcoal": {
      "value": "rgb(31, 38, 46)",
      "metadata": {
        "source": {
          "styleguide": {
            "id": "6593c96ec4165528ed2a9575",
            "name": "Core",
            "platform": "base"
          }
        },
        "resource": {
          "id": "6593e53641ce8c41bf6b08d8",
          "type": "Color"
        }
      },
      "filePath": "design_tokens/zeplin.json",
      "isSource": true,
      "original": {
        "value": "rgb(31, 38, 46)",
        "metadata": {
          "source": {
            "styleguide": {
              "id": "6593c96ec4165528ed2a9575",
              "name": "Core",
              "platform": "base"
            }
          },
          "resource": {
            "id": "6593e53641ce8c41bf6b08d8",
            "type": "Color"
          }
        }
      },
      "name": "colors-charcoal",
      "attributes": {
        "category": "colors",
        "type": "charcoal"
      },
      "path": [
        "colors",
        "charcoal"
      ]
    }
  },
  "textStyles": {
    "heading1": {
      "fontSize": "2rem",
      "fontWeight": "bold",
      "lineHeight": "2.5rem",
      "color": "@blue"
    },
    "paragraph": {
      "fontSize": "1rem",
      "lineHeight": "1.5rem",
      "color": "@charcoal"
    },
    "link": {
      "fontSize": "1rem",
      "lineHeight": "1.5rem",
      "color": "@blueLink"
    }
  },
  "spacing": {
    "small": "0.5rem",
    "medium": "1rem",
    "large": "2rem"
  }
};
