/**
 * This file is automatically generated. Do not edit it directly.
 * Checkout README for more information on how to add a new variable.
 * Generated on Wed Jan 03 2024 18:08:05 GMT+0100 (Central European Standard Time)
 */

export const designTokens = {
  "--font-size-10": "10",
  "--font-size-12": "12",
  "--font-size-14": "14",
  "--font-size-16": "16",
  "--font-size-18": "18",
  "--font-weight-regular": "400",
  "--font-weight-semi-bold": "600",
  "--font-weight-bold": "800",
  "--font-family": "Roboto",
  "--letter-spacing-default": "2%",
  "--letter-spacing-increased": "15%",
  "--letter-spacing-decreased": "-3%",
  "--border-radius-1": "1",
  "--border-radius-2": "2",
  "--border-radius-4": "4",
  "--border-radius-8": "8",
  "--border-width-1": "1",
  "--border-width-2": "2",
  "--box-shadow-v1": {"x":"0","y":"3","blur":"5","spread":"0","color":"rgba(0, 0, 0, 0.2)","type":"dropShadow"},
  "--box-shadow-v2": {"x":"0","y":"4","blur":"16","spread":"0","color":"rgba(0, 0, 0, 0.1)","type":"dropShadow"},
  "--box-shadow-v3": [{"x":"0","y":"7","blur":"50","spread":"0","color":"rgba(0, 0, 0, 0.2)","type":"dropShadow"},{"x":"0","y":"3","blur":"5","spread":"0","color":"rgba(0, 0, 0, 0.2)","type":"dropShadow"}],
  "--z-index-background": -1,
  "--z-index-content": 0,
  "--z-index-content-highlighted": 10,
  "--z-index-header": 20,
  "--z-index-drawer": 30,
  "--z-index-overlay": 40,
  "--colors-white": "rgb(255, 255, 255)",
  "--colors-grey-dark": "rgb(110, 110, 110)",
  "--colors-purple": "rgb(57, 54, 117)",
  "--colors-red": "rgb(181, 69, 69)",
  "--colors-yellow": "rgb(226, 158, 48)",
  "--colors-blue": "rgb(40, 151, 189)",
  "--colors-blue-link": "rgb(15, 76, 168)",
  "--colors-green": "rgb(0, 173, 147)",
  "--colors-grey": "rgb(230, 230, 230)",
  "--colors-charcoal": "rgb(31, 38, 46)"
} as const;